### ISSUE TITLE
无法初始化脚本引擎

### ISSUE THREAD

**Issue by xinge4088** [Mcayear/NewCustomCuiLianPro#3]
[13:33:25 ERROR]: Error occurred while enabling NewCustomCuiLianPro v1.0-SNAPSHOT (Is it up to date?)
java.lang.RuntimeException: Failed to initialize JavaScript engine
        at lvhaoxuan.custom.cuilian.loader.Loader.loadScript(Loader.java:142) ~[original-NewCustomCuiLianPro-1.0-SNAPSHOT.jar:?]
        at lvhaoxuan.custom.cuilian.loader.Loader.loadMoveLevelScript(Loader.java:133) ~[original-NewCustomCuiLianPro-1.0-SNAPSHOT.jar:?]
        at lvhaoxuan.custom.cuilian.movelevel.MoveLevelHandle.init(MoveLevelHandle.java:28) ~[original-NewCustomCuiLianPro-1.0-SNAPSHOT.jar:?]
        at lvhaoxuan.custom.cuilian.NewCustomCuiLianPro.enableConfig(NewCustomCuiLianPro.java:71) ~[original-NewCustomCuiLianPro-1.0-SNAPSHOT.jar:?]
        at lvhaoxuan.custom.cuilian.NewCustomCuiLianPro.onEnable(NewCustomCuiLianPro.java:56) ~[original-NewCustomCuiLianPro-1.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by MooreBilibili** [comment]
一样的报错

**Comment by Mcayear** [comment]
解决：
https://github.com/Mcayear/NewCustomCuiLianPro/releases/tag/1.1.0
